In [1]:
import numpy as np

In [2]:
def sigmoid(inputs):
    sigmoid_scores = [1/ float (1 + np.exp(-x)) for x in inputs]
    return sigmoid_scores

sigmoid_inputs = [-1, 2, 3, 5, 6999]
print('Sigmoid Function Output :: {}'.format(sigmoid(sigmoid_inputs)))

Sigmoid Function Output :: [0.2689414213699951, 0.8807970779778823, 0.9525741268224334, 0.9933071490757153, 1.0]


In [4]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

In [5]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

In [6]:
cancer_data = load_breast_cancer()

In [9]:
cancer_data.data.shape

(569, 30)

In [13]:
trainX, testX, trainY, testY = train_test_split(cancer_data.data, cancer_data.target)

In [14]:
lr.fit(trainX, trainY)

C:\Games\envs\pro\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [15]:
lr.score(testX, testY)

0.965034965034965

In [20]:
lr.predict_proba(testX[:6])

array([[3.31532629e-03, 9.96684674e-01],
       [9.91962797e-01, 8.03720298e-03],
       [9.99471593e-01, 5.28407106e-04],
       [2.27003899e-02, 9.77299610e-01],
       [4.54287403e-03, 9.95457126e-01],
       [3.15460529e-01, 6.84539471e-01]])

In [21]:
lr.predict(testX[:5])

array([1, 0, 0, 1, 1])

In [22]:
testX[:5]

array([[1.106e+01, 1.496e+01, 7.149e+01, 3.739e+02, 1.033e-01, 9.097e-02,
        5.397e-02, 3.341e-02, 1.776e-01, 6.907e-02, 1.601e-01, 8.225e-01,
        1.355e+00, 1.080e+01, 7.416e-03, 1.877e-02, 2.758e-02, 1.010e-02,
        2.348e-02, 2.917e-03, 1.192e+01, 1.990e+01, 7.976e+01, 4.400e+02,
        1.418e-01, 2.210e-01, 2.299e-01, 1.075e-01, 3.301e-01, 9.080e-02],
       [1.757e+01, 1.505e+01, 1.150e+02, 9.551e+02, 9.847e-02, 1.157e-01,
        9.875e-02, 7.953e-02, 1.739e-01, 6.149e-02, 6.003e-01, 8.225e-01,
        4.655e+00, 6.110e+01, 5.627e-03, 3.033e-02, 3.407e-02, 1.354e-02,
        1.925e-02, 3.742e-03, 2.001e+01, 1.952e+01, 1.349e+02, 1.227e+03,
        1.255e-01, 2.812e-01, 2.489e-01, 1.456e-01, 2.756e-01, 7.919e-02],
       [1.425e+01, 2.215e+01, 9.642e+01, 6.457e+02, 1.049e-01, 2.008e-01,
        2.135e-01, 8.653e-02, 1.949e-01, 7.292e-02, 7.036e-01, 1.268e+00,
        5.373e+00, 6.078e+01, 9.407e-03, 7.056e-02, 6.899e-02, 1.848e-02,
        1.700e-02, 6.113e-03, 1.767e